### ISSUE TITLE
bug: toxirc will crash upon receiving commands in irc private message

### ISSUE THREAD

**Issue by Tha14** [endoffile78/toxirc#10]
You can actually make toxirc crash if you send !users, !topic or !characters in a private irc message. The message is parsed as a command and I believe that toxirc will try to use a group number which is not available in the channels array and immediately crash. The solution I've found is not elegant but in irc_callbacks.c I check if the incoming message is from another user in order to not parse it as a command.

**Comment by e0ff** [comment]
Thank you for the fix.
