### ISSUE TITLE
Problem in FreeBSD compiling

### ISSUE THREAD

**Issue by nimopunk** [endoffile78/toxirc#4]

**Comment by nimopunk** [comment]
Hello, just wanted to say that for compiling in freebsd the line <include "sys/stat.h"> must be added in save.c

**Comment by e0ff** [comment]
Ok thank you  for letting know. I just added it.

**Comment by nimopunk** [comment]
I like your project. Was "playing" a bit with it,

**Comment by nimopunk** [comment]
talked to the bot a little :)
