### ISSUE TITLE
Make doesn't do anything, bombs out immediately

### ISSUE THREAD

**Issue by ASmith-** [endoffile78/toxirc#5]
Make doesn't do anything, bombs out immediately

Perhaps its a missing configuration routine is needed to insure whatever this project needs to compile is actually present, dunno because the Make command doesn't tell me anything but No rule to make target.

$ make
make: *** No rule to make target 'third-party/minini/dev/minIni.c', needed by 'all'.  Stop.

**Comment by e0ff** [comment]
Run

```
git submodule init
git submodule update
```

Toxirc uses minini to read the configuration file and its included as a submodule.

**Comment by e0ff** [comment]
I added a rule to the Makefile that will do that: `make deps`
